### ISSUE TITLE
Python pip install

### ISSUE THREAD

**Issue by Jusufs** [SetTrend/plcnext-aptget#1]
Hi.
Thanks for interesting work. Sorry my question It's out of topic. Please delete it if needed.
On a PLCnext with FW 2023.0.0 LTS (23.0.0.65) is a python 3.10.8 version installed. But without pip.
If I need to install e.g. pymodbus [https://pypi.org/project/pymodbus/](url) I need pip installed.
Any idea how to do it please ?
I have a lot of ModbusTCP devices. My idea is to connect this servers from PLCnext AXC F 2152 controller.
Thanks for answer.
Jozef

**Comment by SetTrend** [comment]
Hi Jusufs,

I'm sorry, but I'm not an expert to this regard.

Did you try to google the information? I think there is plenty of very helpful information available:
https://www.google.com/search?q=install+pip+linux+debian

... or you could ask your question on [StackOverflow](https://stackoverflow.com/).

All the best and good luck!
